- name: configuring mysql
  hosts: mysql
  become: yes
  tasks:
  - name: disable current version of MYSQL
    ansible.builtin.command: yum module disable mysql -y

  - name: copy the mysql repo
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: Install MYSQL
    ansible.builtin.yum:
      name: mysql-community-server
      state: installed

  - name: Start service Mysql and enabled
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Set up the root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

