- name: Configure Rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
  - name: configure rabbitmq yum repos
    ansible.builtin.shell: "{{item}}"
    loop:
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

  - name: Install RabbitMQ server
    ansible.builtin.yum:
      name: rabbitmq-server
      state: installed

  - name: restart Rabbitmq
    ansible.builtin.service:
      name: rabbitmq-server
      state: restarted
      enabled: true

  - name: create default user and password
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

  - name: Settimg up the password
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"