- name: Install web components
  hosts: web
  become: yes
  tasks:
  - name: Install Nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  
  - name: Start service nginx, if not started and enabled
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: Remove HTML directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Create HTML directory again
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download catalogue artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: Extract the catalogue artifact
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy roboshop.conf
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: Restart the nginx
    ansible.builtin.service:
      name: nginx
      state: restarted